/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Box007: THREE.Mesh
    Box008: THREE.Mesh
    Glass: THREE.Mesh
    knopka1: THREE.Mesh
    knopka2: THREE.Mesh
    Lastik: THREE.Mesh
    Monitor: THREE.Mesh
    Monitor_base: THREE.Mesh
    Mesh040: THREE.Mesh
    Mesh040_1: THREE.Mesh
    Mesh040_2: THREE.Mesh
    Mesh040_3: THREE.Mesh
    Petlya: THREE.Mesh
    ScreenZone: THREE.Mesh
    Base: THREE.Mesh
    Radiator: THREE.Mesh
    Rectangle020: THREE.Mesh
    Rectangle021: THREE.Mesh
    Line017: THREE.Mesh
    Line018: THREE.Mesh
    Rectangle018: THREE.Mesh
    Rectangle019: THREE.Mesh
    Line015: THREE.Mesh
    Line016: THREE.Mesh
    Rectangle016: THREE.Mesh
    Rectangle017: THREE.Mesh
    Line013: THREE.Mesh
    Line014: THREE.Mesh
    Rectangle015: THREE.Mesh
    Rectangle009: THREE.Mesh
    Line012: THREE.Mesh
    Line011: THREE.Mesh
    Line019: THREE.Mesh
    Box001: THREE.Mesh
    Box002: THREE.Mesh
    Rectangle026: THREE.Mesh
    Keyboard: THREE.Mesh
    Buttons: THREE.Mesh
    Battery: THREE.Mesh
    Mouse: THREE.Mesh
    Mouse_base: THREE.Mesh
    Mesh028: THREE.Mesh
    Mesh028_1: THREE.Mesh
    Legs: THREE.Mesh
    Mesh035: THREE.Mesh
    Mesh035_1: THREE.Mesh
  }
  materials: {
    ['Plastic Serebro']: THREE.MeshStandardMaterial
    Screen: THREE.MeshStandardMaterial
    ['Plastic Serebro 3']: THREE.MeshStandardMaterial
    Monitor: THREE.MeshStandardMaterial
    aluminium: THREE.MeshStandardMaterial
    ['Sterzhen end']: THREE.MeshStandardMaterial
    Sterzhen: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    trackpad: THREE.MeshStandardMaterial
    ['Black Plastic']: THREE.MeshStandardMaterial
    ['White Plastic']: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Keyboard: THREE.MeshStandardMaterial
    ['Grey Plastic']: THREE.MeshStandardMaterial
    Mouse: THREE.MeshStandardMaterial
    Chrome: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/SurfaceStudio.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.04]} rotation={[0.19, 0, 0]} userData={{ name: 'Screen' }}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box007.geometry}
          material={nodes.Box007.material}
          userData={{ name: 'Box007' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box008.geometry}
          material={nodes.Box008.material}
          userData={{ name: 'Box008' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Glass.geometry}
          material={materials.Screen}
          userData={{ name: 'Glass' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.knopka1.geometry}
          material={nodes.knopka1.material}
          userData={{ name: 'knopka1' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.knopka2.geometry}
          material={nodes.knopka2.material}
          userData={{ name: 'knopka2' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lastik.geometry}
          material={nodes.Lastik.material}
          userData={{ name: 'Lastik' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Monitor.geometry}
          material={materials.Monitor}
          userData={{ name: 'Monitor' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Monitor_base.geometry}
          material={nodes.Monitor_base.material}
          userData={{ name: 'Monitor_base' }}
        />
        <group userData={{ name: 'Pen' }}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh040.geometry} material={nodes.Mesh040.material} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh040_1.geometry} material={nodes.Mesh040_1.material} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh040_2.geometry} material={materials.Sterzhen} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh040_3.geometry} material={nodes.Mesh040_3.material} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Petlya.geometry}
          material={nodes.Petlya.material}
          userData={{ name: 'Petlya' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ScreenZone.geometry}
          material={materials['Material.001']}
          userData={{ name: 'ScreenZone' }}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
        material={materials.trackpad}
        userData={{ name: 'Base' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Radiator.geometry}
        material={nodes.Radiator.material}
        userData={{ name: 'Radiator' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle020.geometry}
        material={nodes.Rectangle020.material}
        userData={{ name: 'Rectangle020' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle021.geometry}
        material={nodes.Rectangle021.material}
        userData={{ name: 'Rectangle021' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line017.geometry}
        material={nodes.Line017.material}
        userData={{ name: 'Line017' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line018.geometry}
        material={nodes.Line018.material}
        userData={{ name: 'Line018' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle018.geometry}
        material={nodes.Rectangle018.material}
        userData={{ name: 'Rectangle018' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle019.geometry}
        material={nodes.Rectangle019.material}
        userData={{ name: 'Rectangle019' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line015.geometry}
        material={nodes.Line015.material}
        userData={{ name: 'Line015' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line016.geometry}
        material={nodes.Line016.material}
        userData={{ name: 'Line016' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle016.geometry}
        material={nodes.Rectangle016.material}
        userData={{ name: 'Rectangle016' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle017.geometry}
        material={nodes.Rectangle017.material}
        userData={{ name: 'Rectangle017' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line013.geometry}
        material={nodes.Line013.material}
        userData={{ name: 'Line013' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line014.geometry}
        material={nodes.Line014.material}
        userData={{ name: 'Line014' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle015.geometry}
        material={nodes.Rectangle015.material}
        userData={{ name: 'Rectangle015' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle009.geometry}
        material={nodes.Rectangle009.material}
        userData={{ name: 'Rectangle009' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line012.geometry}
        material={nodes.Line012.material}
        userData={{ name: 'Line012' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line011.geometry}
        material={nodes.Line011.material}
        userData={{ name: 'Line011' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Line019.geometry}
        material={nodes.Line019.material}
        userData={{ name: 'Line019' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box001.geometry}
        material={nodes.Box001.material}
        userData={{ name: 'Box001' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box002.geometry}
        material={nodes.Box002.material}
        userData={{ name: 'Box002' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rectangle026.geometry}
        material={nodes.Rectangle026.material}
        userData={{ name: 'Rectangle026' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Keyboard.geometry}
        material={nodes.Keyboard.material}
        userData={{ name: 'Keyboard' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Buttons.geometry}
        material={materials.Keyboard}
        userData={{ name: 'Buttons' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Battery.geometry}
        material={materials['Grey Plastic']}
        userData={{ name: 'Battery' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse.geometry}
        material={materials.Mouse}
        userData={{ name: 'Mouse' }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mouse_base.geometry}
        material={nodes.Mouse_base.material}
        userData={{ name: 'Mouse_base' }}
      />
      <group userData={{ name: 'Scroll' }}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh028.geometry} material={materials.Chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh028_1.geometry} material={nodes.Mesh028_1.material} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Legs.geometry}
        material={materials.metal}
        userData={{ name: 'Legs' }}
      />
      <group userData={{ name: 'Dial' }}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh035.geometry} material={nodes.Mesh035.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh035_1.geometry} material={nodes.Mesh035_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/SurfaceStudio.glb')
