/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {

  const group = useRef()
  const { nodes, materials } = useGLTF('/models/IPFabric.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.left.geometry} material={materials['SVGMat.005']} />
      <mesh geometry={nodes.Right.geometry} material={materials['SVGMat.004']} />
      <mesh geometry={nodes.center.geometry} material={materials['SVGMat.006']} />
      <mesh geometry={nodes.insetBack.geometry} material={nodes.insetBack.material} />
      <mesh geometry={nodes.insetfront.geometry} material={nodes.insetfront.material} />
    </group>
  )
}

useGLTF.preload('/models/IPFabric.glb')
