/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useLayoutEffect } from 'react'
import { applyProps } from '@react-three/fiber'
import { Html, useGLTF, useTexture, ContactShadows } from '@react-three/drei'
import { MeshStandardMaterial, Color } from 'three'
import { useThree } from '@react-three/fiber'
export function SurfaceStudio(props) {
  const group = useRef()
  const { scene, nodes, materials } = useGLTF('/models/SurfaceStudio2-transformed.glb')
  useLayoutEffect(() => {
    scene.traverse((obj) => obj.isMesh && (obj.receiveShadow = obj.castShadow = true))
  })
  const { camera } = useThree()

  const roughnessMap = useTexture('/img/MonitorBack_R.webp')
  const backMonitor = new MeshStandardMaterial({ metalness: 1, roughnessMap: roughnessMap, color: new Color(0xd0d0d0) })
  const aluminum = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0xd0d0d0) })
  const button = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0xb0b0b0) })
  const blackBase = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x202020) })
  const usb = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x606060) })
  const usbMetal = new MeshStandardMaterial({ metalness: 1, roughness: 0 })
  const test = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x00ff00) })
  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <mesh castShadow receiveShadow geometry={nodes.Base.geometry} material={aluminum} onClick={() => console.log(camera)} />
      <mesh castShadow receiveShadow geometry={nodes.Radiator.geometry} material={blackBase} />

      <mesh castShadow receiveShadow geometry={nodes.Rectangle020.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle021.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Line017.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Line018.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle018.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle019.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Line015.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Line016.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle016.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle017.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Line013.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Line014.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle015.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle009.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Line012.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Line011.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Line019.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Box001.geometry} material={nodes.Box001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Box002.geometry} material={nodes.Box002.material} />
      <mesh castShadow receiveShadow geometry={nodes.Rectangle026.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Keyboard.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Buttons.geometry} material={nodes.Buttons.material} />
      <mesh castShadow receiveShadow geometry={nodes.Battery.geometry} material={button} />
      <mesh castShadow receiveShadow geometry={nodes.Mouse.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Mouse_base.geometry} material={button} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh028.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh028_1.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.Box008.geometry} material={button} />
      <mesh castShadow receiveShadow geometry={nodes.Box007.geometry} material={button} />
      <mesh castShadow receiveShadow geometry={nodes.Monitor_base.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Monitor.geometry} material={backMonitor} />

      <mesh castShadow receiveShadow geometry={nodes.Glass.geometry} material={nodes.Glass.material} />
      <mesh castShadow receiveShadow geometry={nodes.Legs.geometry} material={nodes.Legs.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh035.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh035_1.geometry} material={blackBase} />
      <mesh castShadow receiveShadow geometry={nodes.Lastik.geometry} material={usb} />
      <mesh castShadow receiveShadow geometry={nodes.knopka1.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.knopka2.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Petlya.geometry} material={usbMetal} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh040.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh040_1.geometry} material={aluminum} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh040_2.geometry} material={nodes.Mesh040_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh040_3.geometry} material={nodes.Mesh040_3.material} />

      <mesh castShadow receiveShadow geometry={nodes.ScreenZone.geometry} material={nodes.ScreenZone.material} position={[0, 0, 0]} >

        {/* Drei's HTML component can "hide behind" canvas geometry */}
        <Html className="content" rotation-x={0} position={[0, 0.0, 0]} transform occlude>

        </Html>

      </mesh>
      <ContactShadows position={[0, 0, 0]} scale={20} blur={2} far={4.5} />

    </group>
  )
}

useGLTF.preload('/models//SurfaceStudio2-transformed.glb')
