/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { AccumulativeShadows, RandomizedLight, useGLTF } from '@react-three/drei'
import { MeshStandardMaterial, Color } from 'three'

export function SurfaceStudio(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/SurfaceStudio2-transformed.glb')
  const aluminum = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0xd0d0d0) })
  const button = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0xb0b0b0) })
  const blackBase = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x202020) })


  const usb = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x606060) })
  const usbMetal = new MeshStandardMaterial({ metalness: 1, roughness: 0 })
  const test = new MeshStandardMaterial({ metalness: 1, roughness: .7, color: new Color(0x00ff00) })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={aluminum} />
      <mesh geometry={nodes.Radiator.geometry} material={blackBase} />

      <mesh geometry={nodes.Rectangle020.geometry} material={usb} />
      <mesh geometry={nodes.Rectangle021.geometry} material={usb} />
      <mesh geometry={nodes.Line017.geometry} material={usbMetal} />
      <mesh geometry={nodes.Line018.geometry} material={usbMetal} />
      <mesh geometry={nodes.Rectangle018.geometry} material={usb} />
      <mesh geometry={nodes.Rectangle019.geometry} material={usb} />
      <mesh geometry={nodes.Line015.geometry} material={usbMetal} />
      <mesh geometry={nodes.Line016.geometry} material={usbMetal} />
      <mesh geometry={nodes.Rectangle016.geometry} material={usb} />
      <mesh geometry={nodes.Rectangle017.geometry} material={usb} />
      <mesh geometry={nodes.Line013.geometry} material={usbMetal} />
      <mesh geometry={nodes.Line014.geometry} material={usbMetal} />
      <mesh geometry={nodes.Rectangle015.geometry} material={usb} />
      <mesh geometry={nodes.Rectangle009.geometry} material={usb} />
      <mesh geometry={nodes.Line012.geometry} material={usbMetal} />
      <mesh geometry={nodes.Line011.geometry} material={usbMetal} />
      <mesh geometry={nodes.Line019.geometry} material={usbMetal} />
      <mesh geometry={nodes.Box001.geometry} material={nodes.Box001.material} />
      <mesh geometry={nodes.Box002.geometry} material={nodes.Box002.material} />
      <mesh geometry={nodes.Rectangle026.geometry} material={usb} />
      <mesh geometry={nodes.Keyboard.geometry} material={aluminum} />
      <mesh geometry={nodes.Buttons.geometry} material={nodes.Buttons.material} />
      <mesh geometry={nodes.Battery.geometry} material={button} />
      <mesh geometry={nodes.Mouse.geometry} material={aluminum} />
      <mesh geometry={nodes.Mouse_base.geometry} material={button} />
      <mesh geometry={nodes.Mesh028.geometry} material={usb} />
      <mesh geometry={nodes.Mesh028_1.geometry} material={usb} />
      <mesh geometry={nodes.Box008.geometry} material={button} />
      <mesh geometry={nodes.Box007.geometry} material={button} />
      <mesh geometry={nodes.Monitor_base.geometry} material={aluminum} />
      <mesh geometry={nodes.Monitor.geometry} material={aluminum} />

      <mesh geometry={nodes.Glass.geometry} material={nodes.Glass.material} />
      <mesh geometry={nodes.Legs.geometry} material={nodes.Legs.material} />
      <mesh geometry={nodes.Mesh035.geometry} material={aluminum} />
      <mesh geometry={nodes.Mesh035_1.geometry} material={blackBase} />
      <mesh geometry={nodes.Lastik.geometry} material={usb} />
      <mesh geometry={nodes.knopka1.geometry} material={aluminum} />
      <mesh geometry={nodes.knopka2.geometry} material={aluminum} />
      <mesh geometry={nodes.Petlya.geometry} material={usbMetal} />
      <mesh geometry={nodes.Mesh040.geometry} material={aluminum} />
      <mesh geometry={nodes.Mesh040_1.geometry} material={aluminum} />
      <mesh geometry={nodes.Mesh040_2.geometry} material={nodes.Mesh040_2.material} />
      <mesh geometry={nodes.Mesh040_3.geometry} material={nodes.Mesh040_3.material} />

      <mesh geometry={nodes.ScreenZone.geometry} material={nodes.ScreenZone.material} position={[0, 0, 0]} />


    </group>
  )
}

useGLTF.preload('/models//SurfaceStudio2-transformed.glb')
